apiVersion: v1
items:
- apiVersion: cert-manager.io/v1alpha3
  kind: Issuer
  metadata:
    name: letsencrypt-prod
    namespace: icap-adaptation
  spec:
    acme:
      email: jakub@elastisys.com
      privateKeySecretRef:
        name: letsencrypt-prod
      server: https://acme-v02.api.letsencrypt.org/directory
      solvers:
      - http01:
          ingress:
            class: nginx
        selector: {}
  status:
    acme:
      lastRegisteredEmail: jakub@elastisys.com
      uri: https://acme-v02.api.letsencrypt.org/acme/acct/102690843
    conditions:
    - lastTransitionTime: "2020-11-18T08:39:00Z"
      message: The ACME account was registered with the ACME server
      reason: ACMEAccountRegistered
      status: "True"
      type: Ready
- apiVersion: cert-manager.io/v1alpha3
  kind: Issuer
  metadata:
    name: letsencrypt-staging
    namespace: icap-adaptation
  spec:
    acme:
      email: jakub@elastisys.com
      privateKeySecretRef:
        name: letsencrypt-staging
      server: https://acme-staging-v02.api.letsencrypt.org/directory
      solvers:
      - http01:
          ingress:
            class: nginx
        selector: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""