cloud_provider: aws
environment_name: glasswall-test-ck
oidc_issuer_url: ""
oidc_client_id: kubelogin
oidc_username_claim: email
oidc_groups_claim: groups
s3_es_backup_bucket_name: glasswall-test-ck-es-backup
s3_harbor_bucket_name: glasswall-test-ck-harbor
s3_influx_bucket_name: glasswall-test-ck-influxdb
s3_sc_fluentd_bucket_name: glasswall-test-ck-sc-logs
s3_velero_bucket_name: glasswall-test-ck-velero
s3_region: us-west-1
