cloud_provider: aws
environment_name: glasswall-ck-test
oidc_issuer_url: https://accounts.google.com/o/oauth2/v2/auth
oidc_client_id: kubelogin
oidc_username_claim: email
oidc_groups_claim: groups
s3_es_backup_bucket_name: glasswall-ck-test-es-backup
s3_harbor_bucket_name: glasswall-ck-test-harbor
s3_influx_bucket_name: glasswall-ck-test-influxdb
s3_sc_fluentd_bucket_name: glasswall-ck-test-sc-logs
s3_velero_bucket_name: glasswall-ck-test-velero
s3_region: eu-west-2
