cloud_provider: aws
environment_name: glasswall-ck-test
dns_prefix: glasswall-ck-test
s3_es_backup_bucket_name: glasswall-ck-test-es-backup
s3_harbor_bucket_name: glasswall-ck-test-harbor
s3_influx_bucket_name: glasswall-ck-test-influxdb
s3_sc_fluentd_bucket_name: glasswall-ck-test-sc-logs
s3_velero_bucket_name: glasswall-ck-test-velero
s3_region: us-west-1
