cloud_provider: aws
environment_name: glasswall-dev
oidc_issuer_url: https://accounts.google.com/o/oauth2/v2/auth
oidc_client_id: kubelogin
oidc_username_claim: email
oidc_groups_claim: groups
s3_es_backup_bucket_name: glasswall-dev-es-backup
s3_harbor_bucket_name: glasswall-dev-harbor
s3_influx_bucket_name: glasswall-dev-influxdb
s3_sc_fluentd_bucket_name: glasswall-dev-sc-logs
s3_velero_bucket_name: glasswall-dev-velero
s3_region: us-west-1
